import type { ProposalSettings, ProposalActivity } from './db';

// Default content for the admin-only, confidential League Proposal page.
// Figures are planning targets that the admin edits in the Admin Console.
export function generateInitialProposalSettings(): ProposalSettings {
  const USD_TO_AED = 3.6725;
  const activities: ProposalActivity[] = [
    {
      id: 'activity-web',
      number: 1,
      title: 'Centralized League & Franchise Fan Web Platform & PWA',
      tag: 'Digital Core',
      need: 'Current league and franchise web presence is fragmented across temporary event micro-sites, leading to an 87% fan drop-off between annual 2-week tournament cycles. Fans have no single persistent home for live scores, squads, tickets, and team engagement.',
      relevance: 'T10’s 90-minute format is the most fast-paced, digital-native spectacle in sports. Digital-first Gen-Z audiences expect instant load times, live ball-by-ball simulated telemetry, mobile responsiveness, and continuous 365-day access.',
      what: 'Build and deploy a unified official Abu Dhabi T10 League & 6-Franchise web ecosystem as a Progressive Web App (PWA). Includes automated match schedules, real-time ball-by-ball live tickers, dynamic player & squad dossiers, unified ticketing portal, and automated multilingual content feeds.',
      usdCost: 165000,
      aedCost: Math.round(165000 * USD_TO_AED),
      capexUsd: 110000,
      opexUsd: 55000,
      timeline: 'Months 1-3 (Launch before Season Opener)',
      outcome: 'A world-class digital flagship delivering sub-second load times globally, capturing 750,000+ registered fan accounts in Year 1, and establishing a unified first-party fan data pipeline (CDP).',
      kpis: ['750K+ Registered Users', '4.2M Monthly Page Views', '4.8m Avg Session Duration', 'Sub-800ms Global PWA Latency'],
      franchiseBenefit: 'Direct branded digital home for Arabian Aces and all 5 partner franchises with dedicated sponsor inventory.',
      leagueBenefit: 'Full ownership of first-party fan customer data, increasing media rights valuation by 25%.'
    },
    {
      id: 'activity-forum',
      number: 2,
      title: 'Community Discussion Forum & Real-Time Discourse Engine',
      tag: 'Fan Community',
      need: 'Cricket fans express their passion through passionate tactical debate, match reviews, and player rivalries. In the absence of an official moderated league forum, discussions scatter across Reddit, generic social media, or vanish entirely.',
      relevance: 'Fostering fan community discourse transforms passive broadcast viewers into emotionally invested league brand advocates. Fans build friendships, rivalries, and community identity around franchises.',
      what: 'Deploy an integrated, high-performance community forum where fans can open new discussion threads, post comments, upvote analysis, debate tactical lineups, tag specific franchises, and earn fan points and badges for insightful contributions.',
      usdCost: 45000,
      aedCost: Math.round(45000 * USD_TO_AED),
      capexUsd: 25000,
      opexUsd: 20000,
      timeline: 'Months 2-4 (Pre-Season Buzz & Tourney Active)',
      outcome: 'An active 24/7 fan dialogue hub generating over 65,000 organic discussion threads and 250,000 fan comments per season, driving peer-to-peer viral engagement.',
      kpis: ['65K+ Discussion Threads', '250K+ Community Comments', '38% Monthly Retention Uplift', 'Zero Toxicity via AI Auto-Moderation'],
      franchiseBenefit: 'Exclusive franchise-only fan sub-forums enabling direct team-to-fan Q&As with coaches and players.',
      leagueBenefit: 'Continuous real-time fan sentiment intelligence informing tournament rules and match timings.'
    },
    {
      id: 'activity-competitions',
      number: 3,
      title: 'Gamification Suite: Match Predictors, Trivia & Daily Streaks',
      tag: 'Engagement & Retention',
      need: 'Broadcast sports face a critical battle against short attention spans. Without gamified incentives, fans multi-task on competing entertainment apps during overs and innings breaks.',
      relevance: 'The T10 format generates boundaries on average every 3.2 deliveries, creating frequent high-intensity micro-events ideal for second-screen prediction challenges and boundary betting contests.',
      what: 'A dynamic gamification engine featuring ball-by-ball & match prediction contests, boundary over/under challenges, historical T10 trivia battles, daily check-in streak multipliers (up to 5x), and seasonal fan leaderboards.',
      usdCost: 55000,
      aedCost: Math.round(55000 * USD_TO_AED),
      capexUsd: 35000,
      opexUsd: 20000,
      timeline: 'Months 2-3 (Pre-Season Launch)',
      outcome: 'Triple daily active usage (DAU) across match days, with 60%+ of active users making at least 3 predictions per match, generating 3.5M prediction interactions per tournament.',
      kpis: ['62% Matchday Participation Rate', '3.5M Total Predictions Logged', '45% 7-Day Daily Streak Retention', 'Sponsored Predictor Partner Packages'],
      franchiseBenefit: 'Franchise Fan Wars leaderboard where fan contest points directly elevate their supported team ranking.',
      leagueBenefit: 'Premium commercial inventory: Title sponsorship of Predictor Challenge sold to fintech/telecom partners.'
    },
    {
      id: 'activity-dreamteam',
      number: 4,
      title: '“Dream Team” (Fantasy 10) Squad Architect & Private Leagues',
      tag: 'Fantasy Sports',
      need: 'Fantasy cricket is the #1 driver of deep player familiarity and match viewership worldwide. Traditional fantasy formats take hours; T10 requires a fast, 90-minute optimized 6-player draft.',
      relevance: 'Fans who play fantasy cricket watch 2.4x more overs on television and OTT platforms to monitor their fantasy captain and drafted bowlers in real time.',
      what: 'Build a proprietary "Fantasy 10" squad builder: fans draft a 6-player squad under a strict 55-credit cap, assign a captain (2x multiplier), compete in private friends leagues, and win official franchise rewards.',
      usdCost: 65000,
      aedCost: Math.round(65000 * USD_TO_AED),
      capexUsd: 45000,
      opexUsd: 20000,
      timeline: 'Months 2-4 (Integrated with Live Data Feed)',
      outcome: '300,000+ created Fantasy 10 lineups per season, driving measurable 40%+ increases in linear and digital broadcast watch-time per registered fan.',
      kpis: ['300K+ Fantasy Lineups Created', '12K+ Private Fan Leagues Formed', '2.4x Increase in Broadcast Watch Time', 'Monetized Co-Branded Fantasy Title Sponsor'],
      franchiseBenefit: 'Heightened fan loyalty to individual franchise players (e.g. Moeen Ali, Alex Hales, Nicholas Pooran).',
      leagueBenefit: 'Direct commercial partnership opportunity with global gaming, telecom, or payment partners.'
    },
    {
      id: 'activity-giveaways',
      number: 5,
      title: 'Provably Fair VIP Giveaways & Enclosure Hospitality Passes',
      tag: 'VIP Rewards',
      need: 'Traditional sports sweepstakes are often perceived by fans as non-transparent, untrustworthy, or rigged for influencers, dampening contest participation.',
      relevance: 'Abu Dhabi is globally renowned for luxury, hospitality, and cutting-edge tech. Demonstrating transparent, provably fair mechanics builds profound credibility and aspiration.',
      what: 'A cryptographic SHA-256 verifiable prize draw system offering once-in-a-lifetime experiences: President Box VIP hospitality tickets at Zayed Cricket Stadium, player dugout walks, signed bats, and official team merchandise.',
      usdCost: 120000,
      aedCost: Math.round(120000 * USD_TO_AED),
      capexUsd: 20000,
      opexUsd: 100000,
      timeline: 'Throughout Season & Pre-Tournament',
      outcome: 'Unrivaled fan excitement and viral social sharing, capturing 150,000+ verified giveaway entries and cultivating deep emotional loyalty to Abu Dhabi as the destination of cricket.',
      kpis: ['150K+ Verified Draw Entrants', '100% Cryptographic Audit Trail', '50+ VIP Hospitality Winners Hosted', 'Over 80K User Generated Social Shares'],
      franchiseBenefit: 'Franchises receive allocated VIP dugout guest slots for their top community Superfans.',
      leagueBenefit: 'Positions Abu Dhabi T10 as the most generous and transparent fan-centric league in international sports.'
    },
    {
      id: 'activity-livecenter',
      number: 6,
      title: 'Unified Multi-Team Live Center, Telemetry & Watch Aggregator',
      tag: 'Broadcast Hub',
      need: 'Fans cannot always access linear television feeds across different international broadcast jurisdictions, leading to frustration and pirated illicit streams.',
      relevance: 'Providing a verified centralized hub for ball-by-ball simulated telemetry, official YouTube live press conferences, and synchronized watch parties bridges the broadcast gap.',
      what: 'A centralized multi-match live center embedding official YouTube live streams, pre-match press conferences, player dugout cams, real-time ball-by-ball radar charts, wagon wheels, and live match simulation triggers.',
      usdCost: 60000,
      aedCost: Math.round(60000 * USD_TO_AED),
      capexUsd: 35000,
      opexUsd: 25000,
      timeline: 'Months 2-3 (Live for all 34 tournament fixtures)',
      outcome: '12M+ live telemetry impressions, keeping international fans tethered to the match state even when on mobile or without a TV screen.',
      kpis: ['12M+ Live Scorecard Interactions', '99.98% Telemetry Uptime', 'Over 1.8M YouTube Watch Party Embed Views', 'Real-time Sub-Second Latency'],
      franchiseBenefit: 'Franchises can broadcast team training and behind-the-scenes warmups directly to their fans.',
      leagueBenefit: 'Increases official digital video consumption metrics for OTT and broadcast pitch decks.'
    },
    {
      id: 'activity-socialcurator',
      number: 7,
      title: 'Consolidated Team Social Wall & Cross-Franchise Curator',
      tag: 'Media Aggregator',
      need: 'Fans currently must follow 9 separate Twitter/X accounts, 9 Instagram pages, and 9 YouTube channels, causing fragmented information discovery.',
      relevance: 'Aggregating verified official posts into a singular, high-octane social wall creates a unified "league energy" and lets fans compare teams side-by-side.',
      what: 'Deploy a Curator.io-style multi-platform social aggregator crawling verified team handles across X, Instagram, TikTok, YouTube, Threads, and RSS feeds with auto-curation and admin verification safeguards.',
      usdCost: 35000,
      aedCost: Math.round(35000 * USD_TO_AED),
      capexUsd: 15000,
      opexUsd: 20000,
      timeline: 'Month 1 (Immediate Deployment)',
      outcome: 'One-stop social destination delivering 25,000+ curated multimedia impressions daily, boosting cross-pollination across franchise fanbases.',
      kpis: ['Top 5 Verified Posts / Platform / Team', 'Real-Time Synchronized Feed Updates', '15K Daily Social Wall Views', 'Brand Safety Filter Enforced'],
      franchiseBenefit: 'Smaller or newer franchises gain direct exposure to the collective league fanbase.',
      leagueBenefit: 'Reinforces the ADT10 brand identity as a cohesive international powerhouse.'
    },
    {
      id: 'activity-fanspaces',
      number: 8,
      title: 'Global Physical Fan Spaces & Experiential Clubhouses',
      tag: 'Physical Experiential',
      need: 'Over 80% of ADT10 fans live outside Abu Dhabi (in India, UK, Pakistan, Canada, and the GCC). A tournament restricted solely to the stadium pitch in Abu Dhabi misses the massive global diaspora craving communal match experiences.',
      relevance: 'Sports entertainment brands like the NBA, Premier League, and Formula 1 thrive by building physical experiential lounges in premier metropolitan hubs, creating physical touchpoints that drive merchandise and lifelong fan loyalty.',
      what: 'Design, launch, and operate 5 flagship & pop-up physical "ADT10 Global Fan Clubhouses" in key cricket capital cities: 1) Abu Dhabi (Yas Island / Zayed Stadium precinct), 2) Dubai (Marina / Downtown), 3) London (Regent St / Lord’s precinct pop-up), 4) Mumbai (Bandra Kurla Complex), and 5) Toronto (Brampton / Mississauga). Features include: 360-degree high-definition LED match watch arena, VR Batting Simulator cages against 140km/h T10 bowling, official franchise pop-up merchandise retail, Arabic hospitality barista lounge, and live meetups with team ambassadors & cricket legends.',
      usdCost: 480000,
      aedCost: Math.round(480000 * USD_TO_AED),
      capexUsd: 320000,
      opexUsd: 160000,
      timeline: 'Phased: Abu Dhabi & Dubai (Season 1), London, Mumbai & Toronto (Season 1 Finals & Year 2)',
      outcome: '45,000+ in-person visitors during the tournament cycle, generating $320,000 in official merchandise & F&B sales, and commanding massive local media coverage in the UK, India, UAE, and North America.',
      kpis: ['45K+ In-Person Attendees Across 5 Cities', '15K+ VR Batting Cages Experiences', '$320K+ Direct Retail Merchandise Revenue', 'Over 120 Local Media News Features'],
      franchiseBenefit: 'Direct physical merchandise sales booths for Arabian Aces and all franchise teams in London and Mumbai.',
      leagueBenefit: 'Elevates ADT10 into a physical global lifestyle and sports brand competing directly with F1 and NBA global lounges.'
    },
    {
      id: 'activity-nextgen',
      number: 9,
      title: 'Next-Gen Growth Catalysts: Grassroots Youth Cup & Creator Studio',
      tag: 'Future Growth',
      need: 'Building sustainable multi-generational fan bases requires reaching younger demographics (ages 12-24) through school participation and digital native influencers.',
      relevance: 'Cricket fandom is passed down through youth play and creator culture. Twitch, YouTube, and TikTok content creators drive 60%+ of youth sports discovery.',
      what: 'Launch two high-impact growth programs: 1) "ADT10 School & Grassroots Cup" in UAE and UK schools with 10-over tape-ball tournaments awarding youth cricket equipment and stadium tickets. 2) "ADT10 Global Creator Studio", partnering with 50 top cricket YouTubers & streamers for live watch-along broadcasts and viral trick-shot challenges.',
      usdCost: 140000,
      aedCost: Math.round(140000 * USD_TO_AED),
      capexUsd: 40000,
      opexUsd: 100000,
      timeline: 'Months 3-6 (Rolling Campaign)',
      outcome: 'Direct engagement of 120+ schools, 25,000+ student participants, and 45M+ cross-platform views via creator watch-alongs.',
      kpis: ['120+ Participating Schools & Academies', '50+ Creator Studio Influencers', '45M+ Creator Watch-Along Views', '15K+ New Youth Fan Registrations'],
      franchiseBenefit: 'Scouting pipeline of emerging local UAE and international youth talent for developmental squad slots.',
      leagueBenefit: 'Establishes authentic goodwill, CSR community impact, and deep brand resonance with future generations.'
    }
  ];

  return {
    exchangeRateUsdToAed: USD_TO_AED,
    revenueStreams: {
      predictorSponsorshipUsd: 450000,
      fantasySponsorshipUsd: 350000,
      fanSpacesNamingRightsUsd: 650000,
      merchAndFbUsd: 370000,
      superfanPassportUsers: 38000,
      superfanPassportFeeUsd: 10
    },
    activities,
    updatedAt: new Date().toISOString()
  };
}
